apiVersion: apps/v1
kind: Deployment
metadata:
  name: newkafka-deployment
  namespace: tibco
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: newkafka
        image: phivannam/newkafka:v1
        ports:
            - containerPort: 8084
      hostAliases:
      - hostnames:
        - "my-cluster-kafka-bootstrap"
        ip: "10.101.46.73"
---
apiVersion: v1
kind: Service
metadata:
    name: newkafka-service
    namespace: tibco
spec:
    type: NodePort
    selector:
        bb: web
    ports:
    - port: 8084
      targetPort: 8084
      nodePort: 31084

