apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: new
        image: phivannam/new:v1
        ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
    name: new-service
    namespace: default
spec:
    type: NodePort
    selector:
        bb: web
    ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31082

