apiVersion: apps/v1
kind: Deployment
metadata:
  name: usagelimit-new-deployment
  namespace: tibco
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: usagelimit-new
        image: phivannam/usagelimit_new:v1
        ports:
            - containerPort: 8082
      hostAliases:
      - hostnames:
        - "my-cluster-kafka-bootstrap"
        ip: "10.101.46.73"
---
apiVersion: v1
kind: Service
metadata:
    name: usagelimit-new-service
    namespace: tibco
spec:
    type: NodePort
    selector:
        bb: web
    ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31082
