apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleframework-deployment
  namespace: tibco
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: cleframework
        image: phivannam/cleframework-poc:v2
        ports:
            - containerPort: 8081
      hostAliases:
      - hostnames:
        - "my-cluster-kafka-bootstrap"
        ip: "10.101.46.73"
---
apiVersion: v1
kind: Service
metadata:
    name: cleframework-service
    namespace: tibco
spec:
    type: NodePort
    selector:
        bb: web
    ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31081
