apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: hello
        image: phivannam/hello:v2
        ports:
            - containerPort: 8083
      hostAliases:
      - hostnames:
         - "k8s-worker01"
        ip: "192.168.0.222"
      - hostnames:
        - "k8s-worker02"
        ip: "192.168.0.223"
---
apiVersion: v1
kind: Service
metadata:
    name: hello-service
    namespace: default
spec:
    type: NodePort
    selector:
        bb: web
    ports:
    - port: 8083
      targetPort: 8083
      nodePort: 31083

